In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import linear_model
import pickle
import random
from imblearn.over_sampling import RandomOverSampler

In [76]:
# Read the CSV file into a DataFrame
df = pd.read_csv('condition_filled.csv')
df.columns

Index(['ID mosta', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2023', 'Okres', 'Longitude',
       'Latitude', 'Material', 'Názov mosta', 'Dĺžka premostenia',
       'Rok postavenia', 'Volná šírka mosta', 'Normána zaťažiteľnost',
       'Trieda PK', 'Druh konštrukcie', 'Kraj', 'n_2012', 'n_2013', 'n_2014',
       'n_2015', 'n_2016', 'n_2017', 'n_2018', 'n_2019', 'n_2020', 'n_2021',
       'n_2022', 'n_2023', 'n_length', 'n_width', 'n_region', 'n_class',
       'n_years', 'n_material', 'n_type', 'b_change'],
      dtype='object')

In [80]:
data = df[["ID mosta", 'n_2012', 'n_2013', 'n_2014',
       'n_2015', 'n_2016', 'n_2017', 'n_2018', 'n_2019', 'n_2020', 'n_2021',
       'n_2022', 'n_2023', 'b_change']]

# Filter the DataFrame for rows where "b_change" is equal to 1
filtered_gt = data[data["b_change"] == 1]
filtered_eq = data[data["b_change"] == 0]
filtered_lt = data[data["b_change"] == -1]

# Randomly select 200 rows from the filtered data
random_gt = filtered_gt.sample(n=250, random_state=42)  # Set a random_state for reproducibility
random_eq = filtered_gt.sample(n=250, random_state=42)  # Set a random_state for reproducibility
random_lt = filtered_gt.sample(n=250, random_state=42)  # Set a random_state for reproducibility

# Display the randomly selected 200 rows
print(filtered_gt.shape, filtered_eq.shape, filtered_lt.shape)

(993, 14) (6405, 14) (109, 14)


In [ ]:
'n_2012', 'n_2013', 'n_2014', 'n_2015', 'n_2016', 'n_2017', 'n_2018', 'n_2019', 'n_2020', 'n_2021', 'n_2022', 'n_2023'

In [17]:
matica = np.array([
    [ 11, 21, 31, 41, 51, 61, 71, 81, 91 ],
    [ 12, 22, 32, 42, 52, 62, 72, 82, 92 ],
    [ 13, 23, 33, 43, 53, 63, 73, 83, 93 ],
    [ 14, 24, 34, 44, 54, 64, 74, 84, 94 ],
    [ 15, 25, 35, 45, 55, 65, 75, 85, 95 ],
    [ 16, 26, 36, 46, 56, 66, 76, 86, 96 ],
    [ 17, 27, 37, 47, 57, 67, 77, 87, 97 ],
    [ 18, 28, 38, 48, 58, 68, 78, 88, 98 ],
    [ 19, 29, 39, 49, 59, 69, 79, 89, 99 ]
        ])

X = np.array( matica[:9, :8] )
y = np.array( matica[:9, 8:9] )
X

array([[11, 21, 31, 41, 51, 61, 71, 81],
       [12, 22, 32, 42, 52, 62, 72, 82],
       [13, 23, 33, 43, 53, 63, 73, 83],
       [14, 24, 34, 44, 54, 64, 74, 84],
       [15, 25, 35, 45, 55, 65, 75, 85],
       [16, 26, 36, 46, 56, 66, 76, 86],
       [17, 27, 37, 47, 57, 67, 77, 87],
       [18, 28, 38, 48, 58, 68, 78, 88],
       [19, 29, 39, 49, 59, 69, 79, 89]])

In [14]:
from imblearn.over_sampling import RandomOverSampler

# Create the random oversampler
oversampler = RandomOverSampler(sampling_strategy='auto', random_state=55)

# Apply the oversampler to the data
X_resampled, y_resampled = oversampler.fit_resample(X, y)
X_resampled, y_resampled

(array([[11, 21, 31, 41, 51, 61, 71, 81],
        [12, 22, 32, 42, 52, 62, 72, 82],
        [13, 23, 33, 43, 53, 63, 73, 83],
        [14, 24, 34, 44, 54, 64, 74, 84],
        [15, 25, 35, 45, 55, 65, 75, 85],
        [16, 26, 36, 46, 56, 66, 76, 86],
        [17, 27, 37, 47, 57, 67, 77, 87],
        [18, 28, 38, 48, 58, 68, 78, 88],
        [19, 29, 39, 49, 59, 69, 79, 89]]),
 array([91, 92, 93, 94, 95, 96, 97, 98, 99]))

In [8]:
np.full(5, 5)

array([5, 5, 5, 5, 5])

In [16]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size=1)
print(x_train, "\n")
print(x_test, "\n")
print(y_train, "\n")
print(y_test, "\n")

[[17 27 37 47 57 67 77 87]
 [14 24 34 44 54 64 74 84]
 [11 21 31 41 51 61 71 81]
 [13 23 33 43 53 63 73 83]
 [15 25 35 45 55 65 75 85]
 [16 26 36 46 56 66 76 86]
 [18 28 38 48 58 68 78 88]
 [19 29 39 49 59 69 79 89]] 

[[12 22 32 42 52 62 72 82]] 

[[97]
 [94]
 [91]
 [93]
 [95]
 [96]
 [98]
 [99]] 

[[92]] 



In [22]:
import tensorflow as tf
from tensorflow.keras.utils import plot_model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create a simple Keras model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(10,)))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Visualize the model
plot_model(model, to_file='model.png', show_shapes=True, show_layer_names=True)


You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.
